# Generated by Django 5.2 on 2025-04-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон покупателя'),
        ),
    ]
