# Generated by Django 5.2 on 2025-04-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_feedback_feedback_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон покупателя'),
        ),
    ]
