# Generated by Django 5.2 on 2025-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_feedback_feedback_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': "Зворотній зв'язок покупця", 'verbose_name_plural': "Зворотній зв'язок покупців"},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_email',
            field=models.EmailField(max_length=254, verbose_name='Пошта покупця'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон покупця'),
        ),
    ]
