version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env  # Используйте файл .env для ваших переменных окружения
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      - db  # Обеспечивает зависимость от базы данных
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'carti_leather'        # Используйте переменные из файла .env
      POSTGRES_USER: 'carti'
      POSTGRES_PASSWORD: '113355'
    volumes:
      - db_data:/var/lib/postgresql/data  # Данные базы данных будут сохранены в volume
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./etc/letsencrypt:/etc/letsencrypt
      - static:/app/static
      - media:/app/media
    depends_on:
      - web
    networks:
      - mynetwork

volumes:
  db_data:
  static:
  media:

networks:
  mynetwork:
    driver: bridge
