services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      - db


  db:
    image: sqlite:3
    volumes:
      - db_data:/data/db


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - etc/letsencrypt:/etc/letsencrypt
      - static:/app/static
      - media:/app/media
    depends_on:
      - web

volumes:
  db_data:
  static:
  media: