# Generated by Django 5.2 on 2025-04-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line_2',
        ),
    ]
