# Generated by Django 5.2 on 2025-04-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_shippingaddress_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='feedback_messengers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
