# Generated by Django 5.2 on 2025-05-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_shippingaddress_feedback_messengers'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, unique=True, verbose_name='ID города')),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
            ],
        ),
    ]
