# Generated by Django 5.2 on 2025-05-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
