# Generated by Django 5.2 on 2025-05-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_delete_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='city_ref',
            field=models.CharField(max_length=255),
        ),
    ]
