# Generated by Django 5.2 on 2025-05-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_shippingaddress_city_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city_ref',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='warehouse_ref',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default='Тимчасове місто', max_length=255, verbose_name='Місто'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='office',
            field=models.CharField(default='Тимчасове відділення', max_length=100, verbose_name='Відділення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Створений'), ('processing', 'У процесі'), ('shipped', 'Відправлений'), ('delivered', 'Доставлений'), ('canceled', 'Відмінений')], default='created', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='feedback_messengers',
            field=models.JSONField(blank=True, default=list, verbose_name='Месенджери для звʼязку'),
        ),
    ]
