# Generated by Django 5.2 on 2025-05-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('По передоплаті онлайн', 'cash_pay'), ('cash_online', 'Повна оплата онлайн')], verbose_name='Спосіб оплати'),
        ),
    ]
