# Generated by Django 5.2 on 2025-05-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_pay', 'По передоплаті онлайн'), ('cash_online', 'Повна оплата онлайн')], max_length=20, verbose_name='Спосіб оплати'),
        ),
    ]
