# Generated by Django 5.2 on 2025-05-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='feedback_messengers',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp')], default=1, max_length=20, verbose_name='Месенджери для звʼязку'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='feedback_messengers',
            field=models.TextField(blank=True, help_text='Вибрані месенджери як список через кому', verbose_name='Месенджери для звʼязку'),
        ),
    ]
