# Generated by Django 5.2 on 2025-04-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Товар в кошику', 'verbose_name_plural': 'Товари в кошику'},
        ),
    ]
